### ISSUE TITLE
Updating Pockyt for 3.7

### ISSUE THREAD

**Issue by MordecaiMalignatus** [arvindch/pockyt#13]
Hey there, 

after upgrading my python and seeing the error message, does anything prevent `pockyt` from running on 3.7? As far as I know, there have been breaking changes. 

Many thanks!

**Comment by arvindch** [comment]
Seems to work fine on 3.7 for me. Updated - https://github.com/arvindch/pockyt/releases/tag/1.2.

**Comment by MordecaiMalignatus** [comment]
Thank you, it's greatly appreciated for managing the RSS feed queue that's actually interesting to read!

**Comment by arvindch** [comment]
It's good to know people find this tool useful! :smile:

**Comment by MordecaiMalignatus** [comment]
I use it for reading breaks at work, and to eliminate actually interacting with Pocket as much as I can: 

https://github.com/MordecaiMalignatus/dotfiles/blob/master/fish/functions/ppop.fish

It is very useful indeed!
